= Eclipse JNoSQL
:toc: auto

Eclipse JNoSQL is a compatible implementation of the https://jakarta.ee/specifications/nosql/[Jakarta NoSQL] specification, a Java framework that streamlines the integration of Java applications with NoSQL databases.

== Goals

* Increase productivity performing common NoSQL operations.
* Rich Object Mapping integrated with CDI
* Java-based Query and Fluent-API
* Persistence lifecycle events
* Low-level mapping using Standard NoSQL APIs.
* Specific template API to each NoSQL category.
* Annotation-oriented using JPA-like naming when it makes sense.
* Extensible to explore the particular behavior of a NoSQL database
* Explore the popularity of Apache TinkerPop in Graph API.

== One Mapping API to Multiples NoSQL Databases

Eclipse JNoSQL provides one API for each NoSQL database type. However, it incorporates the same annotations from the https://jakarta.ee/specifications/persistence/[Jakarta Persistence] specification and heritage Java Persistence API (JPA) to map Java objects. Therefore, with just these annotations that look like JPA, there is support for more than twenty NoSQL databases.

[source,java]
----
@Entity
public class Car {

    @Id
    private Long id;
    @Column
    private String name;
    @Column
    private CarType type;
 //...
}
----

Theses annotations from the Mapping API will look familiar to the Jakarta Persistence/JPA developer:

[cols="Annotation description"]
|===
|Annotation|Description

|Entity
|Specifies that the class is an entity. This annotation is applied to the entity class.

|@Id
|Specifies the primary key of an entity.

|@Column
|Specify the mapped column for a persistent property or field.

|@Embeddable
|Specifies a class whose instances are stored as an intrinsic part of an owning entity and share the entity's identity.

|@Convert
|Specifies the conversion of a Basic field or property.

|@MappedSuperclass
|Designates a class whose mapping information is applied to the entities that inherit from it. A mapped superclass has no separate table defined for it.

|@Inheritance
|Specifies the inheritance strategy to be used for an entity class hierarchy.

|@DiscriminatorColumn
|Specifies the discriminator column for the mapping strategy.

|@DiscriminatorValue
|Specifies the value of the discriminator column for entities of the given type.


|===

IMPORTANT: Although similar to JPA, Jakarta NoSQL defines persistable fields with either the `@Id` or `@Column` annotation.

After mapping an entity, you can explore the advantage of using a `Template` interface, which can increase productivity on NoSQL operations.

[source,java]
----
@Inject
Template template;
...

Car ferrari = Car.id(1L).name("Ferrari").type(CarType.SPORT);
template.insert(ferrari);

Optional<Car> car = template.find(Car.class, 1L);
template.delete(Car.class, 1L);
----

This template has specialization to take the benefits of a particular NoSQL database type.

A `Repository` interface is also provided for exploring the Domain-Driven Design (DDD) pattern for a higher abstraction.

[source,java]
----
public interface CarRepository extends Repository<Car, String> {

    Optional<Car> findByName(String name);

}

@Inject
CarRepository repository;
...

Car ferrari = Car.id(1L).name("Ferrari").type(CarType.SPORT);
repository.save(ferrari);
Optional<Car> idResult = repository.findById(1L);
Optional<Car> nameResult = repository.findByName("Ferrari");
----


== Getting Started

Eclipse JNoSQL requires these minimum requirements:

* Java 11 (or higher)
* https://jakarta.ee/specifications/cdi/2.0/[Jakarta Contexts & Dependency Injection 2.0] (CDI)
* https://jakarta.ee/specifications/jsonb/1.0/[Jakarta JSON Binding 1.0] (JSON-B)
* https://jakarta.ee/specifications/jsonp/1.1/[Jakarta JSON Processing 1.1] (JSON-P)
* https://microprofile.io/microprofile-config/[MicroProfile Config]

=== NoSQL Database Types

Eclipse JNoSQL has in common the annotations; thus, the same annotation will work on Column, Document, and so on.; furthermore, the `Template` and the `Repository` are interfaces in common.

Jakarta NoSQL also provides particular behavior to each type; currently, it has support for four NoSQL types:

* Key-Value
* Column Family
* Document
* Graph

=== Key-Value

Jakarta NoSQL provides a Key-Value template to explore the specific behavior of this NoSQL type.

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-key-value</artifactId>
    <version>1.0.0-b4</version>
</dependency>
----

Furthermore, check for a Key-Value communications driver. You can find some implementations in the JNoSQL https://github.com/eclipse/jnosql-communication-driver[Communications Driver API].

[source,java]
----
@Inject
KeyValueTemplate template;
...

Car ferrari = Car.id(1L).name("ferrari").city("Rome").type(CarType.SPORT);

template.put(ferrari);
Optional<Car> car = template.get(1L, Car.class);
template.delete(1L);
----

Key-Value is database agnostic. Thus, you can change the database in your application with no or minimal impact on source code.

=== Column Family

Jakarta NoSQL provides a Column Family template to explore the specific behavior of this NoSQL type.

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-column</artifactId>
    <version>1.0.0-b4</version>
</dependency>
----

Furthermore, check for a Column Family communications driver. You can find some implementations in the JNoSQL https://github.com/eclipse/jnosql-communication-driver[Communications Driver API].

[source,java]
----
@Inject
ColumnTemplate template;
...

Car ferrari = Car.id(1L).name("ferrari").city("Rome").type(CarType.SPORT);

template.insert(ferrari);
Optional<Car> car = template.find(Car.class, 1L);

ColumnDeleteQuery deleteQuery = delete().from("Car").where("_id").eq(1L).build();

template.delete(deleteQuery);

ColumnDeleteQuery query = select().from("Car").where("_id").eq(1L).build();

Optional<Car> result = template.singleResult("select * from Car where _id = 1");
----

Column Family is database agnostic. Thus, you can change the database in your application with no or minimal impact on source code.

=== Document

Jakarta NoSQL provides a Document template to explore the specific behavior of this NoSQL type.

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-document</artifactId>
    <version>1.0.0-b4</version>
</dependency>
----

Furthermore, check for a Document communications driver. You can find some implementations in the JNoSQL https://github.com/eclipse/jnosql-communication-driver[Communications Driver API].

[source,java]
----
@Inject
DocumentTemplate template;
...

Car ferrari = Car.id(1L).name("ferrari").city("Rome").type(CarType.SPORT);

template.insert(ferrari);
Optional<Car> car = template.find(Car.class, 1L);

DocumentDeleteQuery deleteQuery = delete().from("Car").where("_id").eq(1L).build();

template.delete(deleteQuery);

DocumentDeleteQuery query = select().from("Car").where("_id").eq(1L).build();

Optional<Car> result = template.singleResult("select * from Car where _id = 1");
----

Document is database agnostic. Thus, you can change the database in your application with no or minimal impact on source code.

=== Graph

Jakarta NoSQL provides a Graph template to explore the specific behavior of this NoSQL type.

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-graph</artifactId>
    <version>1.0.0-b4</version>
</dependency>
----

Despite the other three Jakarta NoSQL types, Graph does *not* provide a communication layer from Jakarta NoSQL API. Instead, it integrates with https://tinkerpop.apache.org/[Apache Tinkerpop 3x.].

[source,java]
----
@Inject
GraphTemplate template;
...

Category java = Category.of("Java");
Book effectiveJava = Book.of("Effective Java");

template.insert(java);
template.insert(effectiveJava);
EdgeEntity edge = template.edge(java, "is", software);

Stream<Book> books = template.getTraversalVertex().hasLabel("Category").has("name", "Java").in("is").hasLabel("Book").getResult();
----

Apache TinkerPop is database agnostic. Thus, you can change the database in your application with no or minimal impact on source code.

=== Bean Validation

Eclipse JNoSQL provide support for bean validation. It will validate before inserting/updating and constructing an entity.

[source,xml]
----
<dependency>
    <groupId>org.eclipse.jnosql.mapping</groupId>
    <artifactId>mapping-validation</artifactId>
    <version>1.0.0-b4</version>
</dependency>
----

This requires the https://jakarta.ee/specifications/bean-validation/[Jakarta Bean Validation] specification.

[source,java]
----
@Entity
public class Car {

    @Column
    @NotNull
    @Pattern(regexp = "[A-Z]{3}-[0-9]{4}", message = "Invalid car plate")
    private String plate;

    @Column
    @NotNull
    @MonetaryMin(value = "100", message = "There is not car cheap like that")
    @MonetaryMax(value = "1000000", message = "The parking does not support fancy car")
    @CurrencyAccepted(currencies = "USD", message = "The car price must work with USD")
    @Convert(MonetaryAmountConverter.class)
    private MonetaryAmount price;

    @Column
    @NotBlank
    private String model;

    @Column
    @NotBlank
    private String color;
    ...
}
----

[source,java]
----
@Inject
Template template;
...
template.insert(new Car()); // invalid car
----

=== More Information

Check the https://www.jnosql.org/spec/[reference documentation] and https://www.jnosql.org/javadoc/[JavDocs] to learn more.

== Code of Conduct

This project is governed by the Eclipse Foundation Code of Conduct. By participating, you are expected to uphold this code of conduct. Please report unacceptable behavior to codeofconduct@eclipse.org.

== Getting Help

Having trouble with Eclipse JNoSQL? We’d love to help!

Report bugs with Eclipse JNoSQL at https://github.com/eclipse/jnosql.

== Building from Source

You don’t need to build from source to use the project, but if you want to try, you can make it using Maven and Java 11 or higher.

[source, Bash]
----
mvn clean install
----
