// Copyright (c) 2022 Contributors to the Eclipse Foundation
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

==== Querying by Text with the Communication API

The Communication API allows queries to be text. These queries are converted to an operation that already exists in the Manager interface from the `query` method. An `UnsupportedOperationException` is thrown if a NoSQL database doesn't have support for that procedure.

Queries follow these rules:

* All instructions end with a like break `\n`
* It is case-sensitive
* All keywords must be in lowercase
* The goal is to look like SQL, however simpler
* Even if a query has valid sintax a specific implementation may not support an operation. For example, a Column family database may not support queries in a different field that is not the ID field.

===== Key-Value Database Types

Key-Value databases support three operations: `get`, `del` and `put`.

====== `get`

Use the `get` statement to retrie data related to a key

[source,sql]
----
get_statement ::=  get ID (',' ID)*

//examples
get "Apollo" //to return an element where the id is 'Apollo'
get "Diana" "Artemis" //to return a list of values from the keys 
----
====== `del`

Use the `del` statement to delete one or more entities

[source,sql]
----
del_statement ::=  del ID (',' ID)*

//examples
del "Apollo"
del "Diana" "Artemis"
----

====== `put`

Use the `put` statement to either insert or override values

[source,sql]
----
put_statement ::=  put {KEY, VALUE [, TTL]}

//examples
put {"Diana" , "The goddess of hunt"} //adds key 'diana' and value 'The goddess of hunt'
put {"Diana" , "The goddess of hunt", 10 second} //also defines a TTL of 10 seconds
----

===== Column-Family and Document Database Types

The queries have syntax similar to SQL queries. But keep in mind that it has a limitation: joins are not supported. 

They have four operations: `insert`, `update`, `delete`, and `select`.

====== `insert`

Use the `insert` statement to store data for an entity

[source,sql]
----
insert_statement ::=  insert ENTITY_NAME (NAME = VALUE, (`,` NAME = VALUE) *) || JSON [ TTL ]

//examples
insert Deity (name = "Diana", age = 10)
insert Deity (name = "Diana", age = 10, powers = {"sun", "moon"})
insert Deity (name = "Diana", age = 10, powers = {"sun", "moon"}) 1 day
insert Deity {"name": "Diana", "age": 10, "powers": ["hunt", "moon"]}
insert Deity {"name": "Diana", "age": 10, "powers": ["hunt", "moon"]} 1 day

----

====== `update`

Use the `update` statement to update the values of an entity

[source,sql]
----
update_statement ::= update ENTITY_NAME (NAME = VALUE, (`,` NAME = VALUE) *) || JSON

 //examples
update Deity (name = "Diana", age = 10)
update Deity (name = "Diana", age = 10, power = {"hunt", "moon"})
update Deity {"name": "Diana", "age": 10, "power": ["hunt", "moon"]}
----

====== `delete`

Use the `delete` statement to remove fields or entities

[source,sql]
----
delete_statement ::=  delete [ simple_selection ( ',' simple_selection ) ]
                      from ENTITY_NAME
                      [ where WHERE_CLAUSE ]
//examples
delete from Deity
delete power, age from Deity where name = "Diana"
----

====== `select`

The `select` statement reads one or more fields for one or more entities. It returns a result-set of the entities matching the request, where each entity contains the fields corresponding to the query.

[source,sql]
----
select_statement ::=  select ( SELECT_CLAUSE | '*' )
                      from ENTITY_NAME
                      [ where WHERE_CLAUSE ]
                      [ skip (INTEGER) ]
                      [ limit (INTEGER) ]
                      [ order by ORDERING_CLAUSE ]
//examples
select * from Deity
select name, age, adress.age from Deity order by name desc age desc
select * from Deity where birthday between "01-09-1988" and "01-09-1988" and salary = 12
select name, age, adress.age from Deity skip 20 limit 10 order by name desc age desc
----

===== `where`

The `where` keyword specifies a filter (`WHERE_CLAUSE`) to the query. A filter is composed of boolean statements called `conditions` that are combined using `and` or `or` operators.

[source,sql]
----
WHERE_CLAUSE ::= CONDITION ([and | or] CONDITION)*
----

===== Conditions

Conditions are boolean statements that operate on data being queried. They are composed of three elements:

1. *Name*: the data source, or target, to apply the operator
2. *Operator*, defines comparing process between the name and the value.
3. *Value*, that data that receives the operation.

===== Operators

The Operators are:


[cols=2, options=header]
.Operators in a query
|===
| *Operator* | *Description*
| *=*         | Equal to
| *>*         | Greater than
| *<*         | Less than
| *>=*        | Greater than or equal to
| *<=*        | Less than or equal to
| *BETWEEN*   | TRUE if the operand is within the range of comparisons
| *NOT*       | Displays a record if the condition(s) is NOT TRUE
| *AND*       | TRUE if all the conditions separated by AND is TRUE
| *OR*        | TRUE if any of the conditions separated by OR is TRUE
| *LIKE*      |TRUE if the operand matches a pattern
| *IN*        |TRUE if the operand is equal to one of a list of expressions
|===


===== The Value

The value is the last element in a condition, and it defines what'll go to be used, with an operator, in a field target.

There are six types:

* Number is a mathematical object used to count, measure and also label, where if it is a decimal, will become **double**, otherwise, **long**. E.g.: `age = 20`, `salary = 12.12`
* String: one or more characters among either two double quotes, `"`,  or single quotes, `'`. E.g.: `name = "Ada Lovelace"`, `name = 'Ada Lovelace'`
* Convert: convert is a function where given the first value parameter as number or string, it will convert to the class type of the second one. E.g.: `birthday = convert("03-01-1988", java.time.LocalDate)`
* Parameter: the parameter is a dynamic value, which means it does not define the query; it'll replace in the execution time. The parameter is at `@` followed by a name. E.g.: `age = @age`
* Array: A sequence of elements that can be either number or string that is between braces `{  }`. E.g.: `power = {"Sun", "hunt"}`
* JSON: JavaScript Object Notation is a lightweight data-interchange format. E.g.: `siblings = {"apollo": "brother", "zeus": "father"}`



===== `skip`

The `skip` option in a `select` statement defines where the query results should start.

===== `limit`

The `limit` option in a `select` statement limits the number of rows returned by a query.

===== `order by`

The `order by` option allows defining the order of the returned results. It takes as argument (ORDERING_CLAUSE) a list of column names along with the ordering for the column (`asc` for ascendant, which is the default, and `desc` for the descendant).

[source,sql]
----
ORDERING_CLAUSE ::= NAME [asc | desc] ( NAME [asc | desc])*
----

===== TTL

Both the *INSERT* and *PUT* commands support setting a time for data in an entity to expire. It defines the time to live of an object that is composed of the integer value and then the unit that might be `day`, `hour`, `minute`, `second`, `millisecond`, `nanosecond`. E.g.: `ttl 10 second`

===== `PreparedStatement` and `PreparedStatementAsync`

To dynamically run a query, use the `prepare` method in the manager for instance. It will return a `PreparedStatement` interface. To define a parameter to key-value, document, and column query, use the "@" in front of the name.

[source,java]
----
PreparedStatement preparedStatement = documentManager
        .prepare("select * from Person where name = @name");

preparedStatement.bind("name", "Ada");

Stream<DocumentEntity> adas = preparedStatement.getResult();

----

[source,java]
----
PreparedStatementAsync preparedStatement = documentManagerAsync
        .prepare("select * from Person where name = @name");

preparedStatement.bind("name", "Ada");

Consumer<Stream<DocumentEntity>> callback = //instance;

preparedStatement.getResult(callback);

----


WARNING: For more information on Apache TinkerPop and the Gremlin API, please visit this https://tinkerpop.apache.org/gremlin.html[website].
