//
//  Copyright (c) 2018 Otávio Santana and others
//   All rights reserved. This program and the accompanying materials
//   are made available under the terms of the Eclipse Public License v1.0
//   and Apache License v2.0 which accompanies this distribution.
//   The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
//   and the Apache License v2.0 is available at http://www.opensource.org/licenses/apache2.0.php.
//
//   You may elect to redistribute this code under either of these licenses.
//
//   Contributors:
//
//   Otavio Santana

== Mapping API Introduction

The mapping level, to put it differently, has the same goals as either the JPA or ORM. In NoSQL world, the *OxM* then converts the entity object to a communication model.

This level is in charge to do integration among technologies such as Bean Validation. The Mapping API has annotations that make the Java developer’s life easier. As a communication project, it must be extensible and configurable to keep the diversity of NoSQL database.

To go straight and cover the four NoSQL types, this API has four domains:

* `org.jnosql.artemis.column`
* `org.jnosql.artemis.document`
* `org.jnosql.artemis.graph`
* `org.jnosql.artemis.key`

IMPORTANT: The package name might change on the Jakarta EE process.

=== The Mapping structure

The mapping API has six parts:

* The *persistence-core*: The mapping common project.
* The *persistence-configuration*: The configuration in mapper.
* The *persistence-column*: The mapping to column NoSQL database.
* The *persistence-document*: The mapping to document NoSQL database.
* The *persistence-key-value*: The mapping to key-value NoSQL database.
* The *persistence-graph*: The mapping to Graph NoSQL database.
* The *persistence-validation*: The support to Bean Validation

TIP: Each module works separately as a Communication API.

IMPORTANT: Like communication API, there is a support for database diversity. This project has extensions for each database types on the database mapping level.

include::annotations.adoc[]


=== Template classes

The template offers convenient operations to create, update, delete, query, and provides a mapping between your domain objects and communication API. The templates classes have the goal to persist an Entity Model through a communication API. It has three components:

* *Converter*: That converts the Entity to a communication level API.
* *EntityManager*: The EntityManager for communication.
* *Workflow*: That defines the workflow when either you save or update an entity. These events are useful when you, e.g., want to validate data before being saved. See the following picture:

The default workflow has six events:

1. *firePreEntity*: The Object received from mapping.
2. *firePreEntityDataBaseType*:  Just like the previous event, however, to a specific database; in other words, each database has a particular event.
3. *firePreAPI*: The object converted to a communication layer.
4. *firePostAPI*: The entity connection as a response from the database.
5. *firePostEntity*: The entity model from the API low level from the `firePostAPI`.
6. *firePostEntityDataBaseType*: Just like the previous event, however, to a specific database. In other words, each database has a particular event.


include::template_document.adoc[]
include::template_column.adoc[]
include::template_key_value.adoc[]
include::template_graph.adoc[]
include::mapping_query.adoc[]
include::repository.adoc[]
include::pagination.adoc[]
include::bean_validation.adoc[]
