//
//  Copyright (c) 2018 Otávio Santana and others
//   All rights reserved. This program and the accompanying materials
//   are made available under the terms of the Eclipse Public License v1.0
//   and Apache License v2.0 which accompanies this distribution.
//   The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
//   and the Apache License v2.0 is available at http://www.opensource.org/licenses/apache2.0.php.
//
//   You may elect to redistribute this code under either of these licenses.
//
//   Contributors:
//
//   Otavio Santana

====  Querying by text at Mapping API

As in communication layer, the Mapping has a query by text. Both communication and Mapping have the `query` and `prepare` methods, however, at the Mapping API, it will convert the fields and entities to native names from the Entity and Column annotations.

===== Key-Value

In the Key-value database, there is a `KeyValueTemplate` in this NoSQL storage technology. Usually, all the operations are defined by the ID. Therefore, it has a smooth query.
[source,java]
----
KeyValueTemplate template = ...;
List<User> users = template.query("get \"Diana\"");
template.query("remove \"Diana\"");
----


===== Column-Family

The column family has a little more complex structure; however, the search from the key is still recommended. E.g.: Both Cassandra and HBase have a secondary index, yet, neither have a guarantee about performance, and they usually recommend having a second table whose rowkey is your "secondary index" and is only being used to find the rowkey needed for the actual table. Given Person as an entity, then we would like to operate from the field ID, which is the entity from the Entity.


[source,java]
----
ColumnTemplate template = ...;
List<Person> result = template.query("select * from Person where id = 1");
----

TIP: The main difference to run using a template instead of in a manager instance is the template will do a mapper as *ColumnQueryMapperBuilder* does.

===== Document Collection

The document types allow more complex queries, so with more complex entities with a document type, a developer can find from different fields more easily and naturally. Also, there are NoSQL document types that support aggregations query, however, Eclipse JNoSQL does not support this yet. At the Eclipse JNoSQL API perspective, the document and column type is pretty similar, but with the document, a Java developer might do a query from a field that isn't a key and neither returns an unported operation exception or adds a secondary index for this. So, given the same Person entity with document NoSQL type, a developer can do more with queries, such as "person" between "age".

[source,java]
----
DocumentTemplate template = ...;
List<Person> result = template.query("select * from Person where age > 10");
----

TIP: The main difference to run using a template instead of in a manager instance is the template will do a mapper as *DocumentQueryMapperBuilder* does.

===== Graph

If an application needs a recommendation engine or a full detail about the relationship between two entities in your system, it requires a graph database. A graph database has the vertex and the edge. The edge is an object that holds the relationship information about the edges and has direction and properties that make it perfect for maps or human relationship. To the Graph API, Eclipse JNoSQL uses the Apache Tinkerpop. Likewise, the GraphTemplate is a wrapper to convert a Java entity to Vertex in TinkerPop.

[source,java]
----
GraphTemplate template =...;
List<City> cities = template.query("g.V().hasLabel('City')");
----

[source,java]
----
PreparedStatement preparedStatement = documentTemplate.prepare("select * from Person where name = @name");
preparedStatement.bind("name", "Ada");
List<Person> adas = preparedStatement.getResultList();
//to graph just keep using gremlin
PreparedStatement prepare = graphTemplate().prepare("g.V().hasLabel(param)");
prepare.bind("param", "Person");
List<Person> people = preparedStatement.getResultList();
----