//
//  Copyright (c) 2018 Otávio Santana and others
//   All rights reserved. This program and the accompanying materials
//   are made available under the terms of the Eclipse Public License v1.0
//   and Apache License v2.0 which accompanies this distribution.
//   The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
//   and the Apache License v2.0 is available at http://www.opensource.org/licenses/apache2.0.php.
//
//   You may elect to redistribute this code under either of these licenses.
//
//   Contributors:
//
//   Otavio Santana

==== Graph template


The `GraphTemplate` is the column template for synchronous tasks. It has three components:
The `GraphTemplate` is responsible for the persistence of an entity in a Graph database using http://tinkerpop.apache.org/[Apache Tinkerpop]. It is composed basically of three components.

* *GraphConverter*: That converts an entity to communication API, e.g., The Person to Vertex.
* *Graph*: A Graph is a container object for a collection of Vertex, Edge, VertexProperty, and Property objects.
* *GraphWorkflow*: The workflow to update and insert methods.

[source,java]
----
GraphTemplate template = //instance

Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Person personUpdated = template.insert(person);
template.insert(people);
template.insert(person, Duration.ofHours(1L));

template.update(person);
template.update(people);
----

===== Create the Relationship Between Them (EdgeEntity)

[source,java]
----
Person poliana =...//instance;
Book shack =...//instance;
EdgeEntity edge = graphTemplate.edge(poliana, "reads", shack);
reads.add("where", "Brazil");
Person out = edge.getOutgoing();
Book in = edge.getIncoming();
----

===== Querying with traversal

Traversals in Gremlin are spawned from a TraversalSource. The GraphTraversalSource is the typical "graph-oriented" DSL used throughout the documentation and will most likely be the most used DSL in a TinkerPop application.

To run a query in Graph with Gremlin, there are traversal interfaces. These interfaces are lazy; in other words, they just run after any finalizing method.

E.g.:

In the scenario, there is a marketing campaign, and the target is:

* An engineer
* The salary is higher than $3,000
* The age is between 20 and 25 years old

[source,java]
----
List<Person> developers = graph.getTraversalVertex()
       .has("salary", gte(3_000D))
       .has("age", between(20, 25))
       .has("occupation", "Developer")
       .<Person>stream().collect(toList());
----


The next step is to return the engineer's friends.

[source,java]
----
List<Person> developers = graph.getTraversalVertex()
        .has("salary", gte(3_000D))
        .has("age", between(20, 25))
        .has("occupation", "Developer")
        .<Person>stream().out("knows").collect(toList());
----


To use a graph template, just follow the CDI style and put an `@Inject` on the field.

[source,java]
----
@Inject
private GraphTemplate template;
----

The next step: make a *Graph* instance eligible to CDI, applying the producers method:

[source,java]
----
@Produces
public Graph getManager() {
    Graph graph = //instance
    return graph;
}
----

To work with more than one Graph Template, there are two approaches:

1) Using qualifiers:

[source,java]
----
@Inject
@Database(value = DatabaseType.GRAPH, provider = "databaseA")
private GraphTemplate templateA;

@Inject
@Database(value = DatabaseType.GRAPH, provider = "databaseB")
private GraphTemplate templateB;


//producers methods
@Produces
@Database(value = DatabaseType.GRAPH, provider = "databaseA")
public Graph getManagerA() {
    Graph manager =//instance
    return graph;
}

@Produces
@Database(value = DatabaseType.GRAPH, provider = "databaseB")
public Graph getManagerB() {
    Graph graph = //instance
    return graph;
}
----

2)  Using the *GraphTemplateProducer* class:

[source,java]
----
@Inject
private GraphTemplateProducer producer;

public void sample() {
   Graph graphA = //instance;
   Graph graphB = //instance
   GraphTemplate templateA = producer.get(graphA);
   GraphTemplate templateB = producer.get(graphB);
}
----