//
//  Copyright (c) 2018 Otávio Santana and others
//   All rights reserved. This program and the accompanying materials
//   are made available under the terms of the Eclipse Public License v1.0
//   and Apache License v2.0 which accompanies this distribution.
//   The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
//   and the Apache License v2.0 is available at http://www.opensource.org/licenses/apache2.0.php.
//
//   You may elect to redistribute this code under either of these licenses.
//
//   Contributors:
//
//   Otavio Santana

==== DocumentTemplate

This template has the duty to be a bridge between the entity model and communication API to document collection. It has two classes; `DocumentTemplate` and `DocumentTemplateAsync` - one for the synchronous and the other for the asynchronous work.


The `DocumentTemplate` is the document template for the synchronous tasks. It has three components:

* *DocumentEntityConverter*: That converts an entity to communication API, e.g., The Person to DocumentEntity.

* *DocumentCollectionManager*: The document collection entity manager.

* *DocumentWorkflow*: The workflow to update and insert methods.

[source,java]
----
DocumentTemplate template = //instance

Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Person personUpdated = template.insert(person);
template.insert(people);
template.insert(person, Duration.ofHours(1L));

template.update(person);
template.update(people);
----

To both remove and retrieve information from document collection, there are *DocumentQuery* and *DocumentDeleteQuery*.

[source,java]
----
DocumentQuery query = select().from("Person").where("address").eq("Olympus").build();

List<Person> peopleWhoLiveOnOlympus = template.find(query);
Optional<Person> artemis = template.singleResult(select().from("Person")
                .where("nickname").eq("artemis").build());

DocumentDeleteQuery deleteQuery = delete().from("Person").where("address").eq("Olympus").build();
template.delete(deleteQuery);
----

Both *DocumentQuery* and *DocumentDeleteQuery* query won't convert the Object to native fields. However, there is *DocumentQueryMapperBuilder* that creates both queries types reading the Class then switching to the native fields through annotations.

[source,java]
----
@Entity
public class Person {

    @Id("native_id")
    private long id;

    @Column
    private String name;

    @Column
    private int age;
}
----

[source,java]
----
@Inject
private DocumentQueryMapperBuilder mapperBuilder;

public void mapper() {
  DocumentQuery query = mapperBuilder.selectFrom(Person.class).where("id").gte(10).build();
  //translating: select().from("Person").where("native_id").gte(10L).build();
  DocumentDeleteQuery deleteQuery = mapperBuilder.deleteFrom(Person.class).where("id").eq("20").build();
  //translating: delete().from("Person").where("native_id").gte(10L).build();
}
----


To use a document template, just follow the CDI style and put an `@Inject` on the field.

[source,java]
----
@Inject
private DocumentTemplate template;
----

The next step is to produce a **DocumentCollectionManager:**

[source,java]
----
@Produces
public DocumentCollectionManager getManager() {
    DocumentCollectionManager manager = //instance
    return manager;
}
----

To work with more than one Document Template, there are two approaches:

1) Using qualifiers:

[source,java]
----
@Inject
@Database(value = DatabaseType.DOCUMENT, provider = "databaseA")
private DocumentTemplate templateA;

@Inject
@Database(value = DatabaseType.DOCUMENT, provider = "databaseB")
private DocumentTemplate templateB;


//producers methods
@Produces
@Database(value = DatabaseType.DOCUMENT, provider = "databaseA")
public DocumentCollectionManager getManagerA() {
    DocumentCollectionManager manager = //instance
    return manager;
}

@Produces
@Database(value = DatabaseType.DOCUMENT, provider = "databaseB")
public DocumentCollectionManager getManagerB() {
    DocumentCollectionManager manager = //instance
    return manager;
}
----

2) Using the *DocumentTemplateProducer* class:

[source,java]
----
@Inject
private DocumentTemplateProducer producer;

public void sample() {
   DocumentCollectionManager managerA = //instance;
   DocumentCollectionManager managerB = //instance
   DocumentTemplate templateA = producer.get(managerA);
   DocumentTemplate templateB = producer.get(managerB);
}
----

==== DocumentTemplateAsync

The `DocumentTemplateAsync` is the document template for the asynchronous tasks. It has two components:

* *DocumentEntityConverter:* That converts an entity to communication API, e.g., The Person to DocumentEntity.

* *DocumentCollectionManagerAsync:* The asynchronous document collection entity manager.

[source,java]
----
DocumentTemplateAsync templateAsync = //instance

Person person = new Person();
person.setAddress("Olympus");
person.setName("Artemis Good");
person.setPhones(Arrays.asList("55 11 94320121", "55 11 94320121"));
person.setNickname("artemis");

List<Person> people = Collections.singletonList(person);

Consumer<Person> callback = p -> {};
templateAsync.insert(person);
templateAsync.insert(person, Duration.ofHours(1L));
templateAsync.insert(person, callback);
templateAsync.insert(people);

templateAsync.update(person);
templateAsync.update(person, callback);
templateAsync.update(people);
----

For information removal and retrieval, there are *DocumentQuery* and *DocumentDeleteQuery* respectively; also, the callback method can be used.
[source,java]
----
Consumer<List<Person>> callBackPeople = p -> {};
Consumer<Void> voidCallBack = v ->{};
templateAsync.find(query, callBackPeople);
templateAsync.delete(deleteQuery);
templateAsync.delete(deleteQuery, voidCallBack);
----

To use a document template, just follow the CDI style and put an `@Inject` on the field.

[source,java]
----
@Inject
private DocumentTemplateAsync template;
----

The next step is to produce a **DocumentCollectionManagerAsync:**

[source,java]
----
@Produces
public DocumentCollectionManagerAsync getManager() {
    DocumentCollectionManagerAsync managerAsync = //instance
    return manager;
}
----

To work with more than one Document Template, there are two approaches:

1) Using qualifiers:

[source,java]
----
@Inject
@Database(value = DatabaseType.DOCUMENT, provider = "databaseA")
private DocumentTemplateAsync templateA;

@Inject
@Database(value = DatabaseType.DOCUMENT, provider = "databaseB")
private DocumentTemplateAsync templateB;


//producers methods
@Produces
@Database(value = DatabaseType.DOCUMENT, provider = "databaseA")
public DocumentCollectionManagerAsync getManagerA() {
   DocumentCollectionManager manager = //instance
   return manager;
}

@Produces
@Database(value = DatabaseType.DOCUMENT, provider = "databaseB")
public DocumentCollectionManagerAsync getManagerB() {
    DocumentCollectionManager manager = //instance
    return manager;
}
----

2) Using the *DocumentTemplateAsyncProducer*:

[source,java]
----
@Inject
private DocumentTemplateAsyncProducer producer;

public void sample() {
   DocumentCollectionManagerAsync managerA = //instance;
   DocumentCollectionManagerAsync managerB = //instance
   DocumentTemplateAsync templateA = producer.get(managerA);
   DocumentTemplateAsync templateB = producer.get(managerB);
}
----